onboarding = false

[ui]
mouse_capture = true
copy_on_select = true
show_agent_labels_on_pane_borders = true

[ui.toast]
delivery = "herdr"

[terminal]
new_cwd = "follow"

[keys]
prefix = "ctrl+b"
detach = "prefix+d"
reload_config = "prefix+shift+r"
settings = "prefix+comma"
goto = "prefix+shift+s"
copy_mode = "prefix+["
split_horizontal = "prefix+s"
split_vertical = "prefix+v"
zoom = "prefix+m"
resize_mode = "prefix+z"
close_pane = "prefix+x"
swap_pane_left = "prefix+shift+h"
swap_pane_down = "prefix+shift+j"
swap_pane_up = "prefix+shift+k"
swap_pane_right = "prefix+shift+l"
new_tab = "prefix+c"
close_tab = "prefix+ampersand"
rename_tab = "prefix+r"
next_tab = ["prefix+n", "prefix+ctrl+n"]
previous_tab = ["prefix+p", "prefix+ctrl+p"]
next_agent = "prefix+a"
previous_agent = "prefix+shift+a"
focus_agent = "prefix+ctrl+1..9"
new_worktree = "prefix+shift+g"
open_worktree = "prefix+shift+o"
remove_worktree = "prefix+shift+x"

[[keys.command]]
key = "prefix+g"
type = "pane"
command = "lazygit 2> /dev/null"
description = "lazygit"

[[keys.command]]
key = "ctrl+h"
type = "plugin_action"
command = "vim-herdr-navigation.left"
description = "navigate left (vim/herdr)"

[[keys.command]]
key = "ctrl+j"
type = "plugin_action"
command = "vim-herdr-navigation.down"
description = "navigate down (vim/herdr)"

[[keys.command]]
key = "ctrl+k"
type = "plugin_action"
command = "vim-herdr-navigation.up"
description = "navigate up (vim/herdr)"

[[keys.command]]
key = "ctrl+l"
type = "plugin_action"
command = "vim-herdr-navigation.right"
description = "navigate right (vim/herdr)"

[experimental]
kitty_graphics = true

[theme]
name = "catppuccin"
auto_switch = true
light_name = "catppuccin-latte"
dark_name = "catppuccin"
